define([], function() {
  return {
    "PropertyPaneDescription": "Write 1-3 sentences describing the functionality of this component.",
    "TitleFieldLabel": "Card title",
    "CommonLeaveRequest": "Leave request",
    "SubTitle": "Quick view",
    "PhraseYouHaveHoursAnnualLeave": "{0} hours annual leave currently available",
    "PhraseYouHaveHoursAnnualLeaveWithUnapproved": "{0} hours annual leave currently available, and {1} hours yet to be approved",
    "PhraseLookingUpYourAnnualLeave": "Looking up your annual leave...",
    "PhraseCannotFindAnyAnnualLeave": "Cannot find any annual leave",
    "Description": "Create your SPFx Adaptive Card Extension solution!",
    "CommonRequestLeave": "Request leave",
    "CommonLeaveBalances": "Leave balances",
    "CommonAnnualLeave": "Annual leave",
    "CommonSickLeave": "Sick leave",
    "CommonLongServiceLeave": "Long service leave",
    "CommonCommunityServiceLeave": "Community service leave",
    "CommonParentalLeave": "Parental leave",
    "CommonFamilyLeave": "Family or domestic violence leave",
    "CommonStartDate": "Start date",
    "CommonReturnToWork": "Return to work",
    "CommonSelectDate": "Select date",
    "CommonPleaseSelectADate": "Please select a date",
    "CommonCalculatedHours": "Calculated hours",
    "PhraseThisWillBeFilledWhen": "This will be filled automatically when dates are selected",
    "CommonCalculateHours": "Calculate hours",
    "CommonHours": "hours",
    "CommonSubmitForApproval": "Submit for approval"
  }
});